name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build Package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install twine
        docker run --rm -v $(pwd):/io konstin2/maturin build --release
        twine upload target/wheels/*

  deploy-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build Package
      env:
        MATURIN_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install maturin
        maturin publish -u __token__

  deploy-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build Package
      env:
        MATURIN_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install maturin
        maturin publish -u __token__
