name: Publish to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build Package
      env:
        PYO3_PACK_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install pyo3-pack
        pyo3-pack publish -u __token__
